name: Test Submit Sitemaps Action

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master

permissions: read-all

jobs:
  test-submit-sitemaps-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install dependencies
        shell: bash
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Submit URLs from single sitemap to IndexNow
        run: >
          python src/helper/submit.py
          --host jakob-bagterp.github.io
          --api-key 6d71a14ac15c4c41a0c19e641f659208
          --api-key-location https://jakob-bagterp.github.io/index-now-api-key.txt
          --endpoint yandex
          --sitemap-locations https://jakob-bagterp.github.io/index-now-submit-sitemap-urls-action/sitemap.xml
      - name: Submit multiple URLs to IndexNow
        run: >
          python src/helper/submit.py
          --host jakob-bagterp.github.io
          --api-key 6d71a14ac15c4c41a0c19e641f659208
          --api-key-location https://jakob-bagterp.github.io/index-now-api-key.txt
          --endpoint yandex
          --sitemap-locations "
            https://jakob-bagterp.github.io/sitemap.xml
            https://jakob-bagterp.github.io/index-now-submit-sitemap-urls-action/sitemap.xml"
